exe{privet}: {hxx ixx txx cxx}{**} testscript

cxx.poptions =+ "-I$out_root" "-I$src_root"

if ($build.version.number <= 14999990000) # <= 0.14.x
  cxx.coptions += ($cxx.id == 'msvc' ? /utf-8 : -finput-charset=UTF-8)
